# Generated by Django 4.1.7 on 2023-03-20 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=200)),
                ("competence", models.CharField(max_length=1000)),
                ("langue", models.CharField(max_length=500)),
                ("interet", models.CharField(max_length=500)),
                ("objectif", models.TextField()),
                ("experience", models.TextField()),
                ("education", models.TextField()),
                ("projet", models.TextField()),
                ("date_added", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["-date_added"],},
        ),
    ]
