# Generated by Django 4.1.7 on 2023-03-22 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pdf", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="photos"),
        ),
        migrations.AddField(
            model_name="profile",
            name="titre",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
