# Generated by Django 4.1.7 on 2023-03-23 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pdf", "0002_profile_photo_profile_titre"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="objectif",),
        migrations.RemoveField(model_name="profile", name="projet",),
    ]
